name: zhima

on:
  workflow_dispatch:
  schedule:
     - cron: '5 0-15 * * *'
  watch:
    types: started
  repository_dispatch:
    types: dkd
    
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【zhima】'
        run: |
          node zhima.js
        env:
          ZM_COOKIES: ${{ secrets.ZM_COOKIES }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
